### ISSUE TITLE
Conversion of TCP profile failing using vscode ACC Chariot extension

### ISSUE THREAD

**Issue by ajgerace** [f5devcentral/f5-automation-config-converter#49]
### Environment
* F5 Extension version: v3.1.0
* F5 ACC Chariot version: v1.13.0

### Summary
Attempting to convert a TCP profile using the VScode F5 Extension with the ACC Chariot extension fails to convert and throws an error and nothing is converted

### Steps To Reproduce
1. Convert following config snippet:
```conf
ltm profile tcp mytcp-progressive {
    app-service none
    auto-proxy-buffer-size enabled
    auto-receive-window-size enabled
    auto-send-buffer-size enabled
    congestion-control woodside
    defaults-from tcp
    init-cwnd 16
    init-rwnd 16
    nagle auto
    proxy-buffer-high 262144
    proxy-buffer-low 196608
    push-flag auto
    receive-window-size 131072
    send-buffer-size 262144
}
```

2. Observe the following error message:
```[2021-08-25T21:29:38.351Z] [INFO]: f5.chariot.convert called
[2021-08-25T21:29:38.352Z] [INFO]: f5.chariot.convert text found
[2021-08-25T21:29:38.353Z] [ERROR]: f5.chariot.convert failed with [TypeError: Cannot read property 'endsWith' of undefined
	at module.exports (/Users/gerace/.vscode/extensions/f5devcentral.vscode-f5-chariot-1.13.0/node_modules/f5-as3-config-converter/src/util/convert/findLocation.js:33:24)
	at module.exports (/Users/gerace/.vscode/extensions/f5devcentral.vscode-f5-chariot-1.13.0/node_modules/f5-as3-config-converter/src/removeIapp.js:27:21)
	at mainRunner (/Users/gerace/.vscode/extensions/f5devcentral.vscode-f5-chariot-1.13.0/node_modules/f5-as3-config-converter/src/main.js:50:28)
	at Object.mainAPI (/Users/gerace/.vscode/extensions/f5devcentral.vscode-f5-chariot-1.13.0/node_modules/f5-as3-config-converter/src/main.js:175:30)
	at /Users/gerace/.vscode/extensions/f5devcentral.vscode-f5-chariot-1.13.0/out/extension.js:76:62
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/gerace/.vscode/extensions/f5devcentral.vscode-f5-chariot-1.13.0/out/extension.js:67:20]

```

### Expected Behavior
An AS3 declaration with the TCP profile is to be created.

### Actual Behavior
Nothing is outputted and an error occurs in output window.

**Comment by mdditt2000** [comment]
Merge branch 'CHARON-433-location-bug' into 'develop'. --- Resolved
