### ISSUE TITLE
Error converting configuration file

### ISSUE THREAD

**Issue by azahajkiewicz** [f5devcentral/f5-automation-config-converter#56]
### Environment
 * Application Services Version: 1.15.0
 * BIG-IP Version: - 

### Summary
Cannot convert bigip.conf.

### Steps To Reproduce
1. Convert following config:
```conf
This is a client configuration, cannot be disclosed.
```

2. Observe the following error message:
```tenant_2/bigip.conf
Error parsing input file. Please email us at solutionsfeedback@f5.com and include the following error:

(node:1) UnhandledPromiseRejectionWarning: TypeError: Error parsing input file. Please email us at solutionsfeedback@f5.com and include the following error:
Cannot read property 'length' of undefined
    at groupObjects (/app/src/parse.js:171:52)
    at module.exports (/app/src/parse.js:271:27)
    at mainRunner (/app/src/main.js:37:18)
    at main (/app/src/main.js:131:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

```tenant_50/bigip.conf, tenant_72/ bigip.conf
2021-09-21 17:07:21 ERROR Error extracting application. Please email us at solutionsfeedback@f5.com and include the following error:

2021-09-21 17:07:21 ERROR Cannot read property 'Shared' of undefined
```

### Expected Behavior
Configuration translated or marked as unsupported.

For the configuration file, please reach out to a.zahajkiewicz@f5.com

**Comment by p-semenov-f5** [comment]
Issue opened for AS3:
https://github.com/F5Networks/f5-appsvcs-extension/issues/513

**Comment by p-semenov-f5** [comment]
https://jira.pdsea.f5net.com/browse/CHARON-463
