### ISSUE TITLE
f5.chariot.convertDO failed with [TypeError: doc.getText is not a function

### ISSUE THREAD

**Issue by pmawan** [f5devcentral/f5-automation-config-converter#76]
### Environment
 * ACC Version: 1.17
 * AS3 Version:3.3.0
 * BIG-IP Version:16.1

### Summary
i get the following error when i try to convert a virtual server 
f5.chariot.convertDO failed with [TypeError: doc.getText is not a function
9 [2021-12-25T02:53:57.496Z] [ERROR]: f5.chariot.convertAS3 failed with [TypeError: doc.getText is not a function
	at getEditorText (c:\Users\awan_m\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.17.0\out\util.js:81:24)
	at c:\Users\awan_m\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.17.0\out\extension.js:73:51
	at S._withProgress (c:\Users\awan_m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:45568)
	at S.withProgress (c:\Users\awan_m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:45322)
	at Object.withProgress (c:\Users\awan_m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30872)
	at c:\Users\awan_m\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.17.0\out\extension.js:69:38
### Steps To Reproduce

right click on the VIp - from imported ucs - convert to AS3 with ACC - getting the below error

2. Observe the following error message:

9 [2021-12-25T02:53:57.496Z] [ERROR]: f5.chariot.convertAS3 failed with [TypeError: doc.getText is not a function
	at getEditorText (c:\Users\awan_m\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.17.0\out\util.js:81:24)
	at c:\Users\awan_m\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.17.0\out\extension.js:73:51
	at S._withProgress (c:\Users\awan_m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:45568)
	at S.withProgress (c:\Users\awan_m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:45322)
	at Object.withProgress (c:\Users\awan_m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30872)
	at c:\Users\awan_m\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.17.0\out\extension.js:69:38

**Comment by DumpySquare** [comment]
Hi!  Can you provide a screenshot and/or a sanitized version of the application configuration?

**Comment by DumpySquare** [comment]
And to be clear, this is probably an error with the vscode-f5-chariot project not this project.  Can you open this issue here: https://github.com/f5devcentral/vscode-f5-chariot?

**Comment by pmawan** [comment]
thanks for the reply - ye - it is with VS code and i have added an issue to vs chariot

**Comment by sschadwick** [comment]
Issue moved to f5devcentral/vscode-f5-chariot, marking as closed.
