### ISSUE TITLE
Error - Missing or mis-indented '}' for line: '    order-info "{' - appears related to cert-order-manager

### ISSUE THREAD

**Issue by nwehrman** [f5devcentral/f5-automation-config-converter#90]
### Environment
 * ACC Version: Latest 1.22.0
 * AS3 Version: 3.36.1
 * BIG-IP Version: 15.1.6

### Summary
Please also include information about the reproducibility and the severity/impact of the issue.

### Steps To Reproduce
1. Place this code inside bigip.conf

sys crypto cert-order-manager /Common/Cert_Manager_test {
    additional-headers customerUri:test.com
    authority comodo
    base-url https://cert-manager.com/
    ca-cert /Common/ca-bundle.crt
    internal-proxy /Common/www.test.com
    login-name nate
    login-password $M$wx$bs7xF0C95wyBN6VNT326MA==
    order-info "{
        orgId 1
        certType 1
        serverType -1
    }"
    validity-days 365
}

generate a ucs
run that ucs through acc
Error is returned:
nate@ldap:/var/tmp$ sudo docker run --rm -v  "$PWD":/app/data f5devcentral/f5-automation-config-converter -o bgp_config.json -u data/bgp_test.ucs
/app/src/engines/parser.js:58
                        throw new Error(`Missing or mis-indented '}' for line: '${arr[i]}'`);
                              ^

Error: Error parsing input file. Please open an issue at https://github.com/f5devcentral/f5-automation-config-converter/issues and include the following error:
Missing or mis-indented '}' for line: '    order-info "{'
    at orchestrate (/app/src/engines/parser.js:58:31)
    at /app/src/engines/parser.js:268:65
    at Array.map (<anonymous>)
    at /app/src/engines/parser.js:268:52
    at Array.forEach (<anonymous>)
    at module.exports (/app/src/engines/parser.js:197:28)
    at mainRunner (/app/src/main.js:98:18)
    at main (/app/src/main.js:187:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```



### Expected Behavior
No error

### Actual Behavior
ACC fails to complete

**Comment by mdditt2000** [comment]
Afternoon @nwehrman Please can you send/point me to your **bgp_test.ucs** file. Reach out to me at automation_toolchain_pm@f5.com

**Comment by mdditt2000** [comment]
Created CHARON-729 for PM tracking
