### ISSUE TITLE
Docker run doesnt work to generate JSON output file

### ISSUE THREAD

**Issue by Sathishkunisai** [f5devcentral/f5-automation-config-converter#94]
### Environment
 * ACC Version:
 * AS3 Version:
 * BIG-IP Version:

### Summary

```
In V15 F5 box, ran below cmd to generate UCCS file
`
 tmsh save sys ucs ucs-bigiq-04022018.ucs 
`



Ran a docker command to load UCS and covert to JSON format...

$



2. Observe the following error message:
`
$ docker run  -v "$PWD":/app/data f5devcentral/f5-automation-config-converter:latest -o /data/output.json -u ucs-bigiq-04022018.ucs --summary
2022-12-09 21:35:11 ERROR undefined
/app/src/preConverter/extract.js:59
        throw new Error('Error extracting UCS');
              ^

Error: Error extracting UCS
    at /app/src/preConverter/extract.js:59:15
    at async Promise.all (index 0)
    at async main (/app/src/main.js:180:20)
bash-5.1.8 (01:35:11) m-c02zd2yvlvdq@s0r04i4:~/ucs-f5-json >
`


### Expected Behavior
A clear and concise description of what you expected to happen.

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

**Comment by fredlem2** [comment]
Is there any solution for this bug ?
Thanks a lot
REgards
